import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { MenuComponent } from "../components/menu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full ">
        <MenuComponent />
        {children}
        {/* Footer minimalista de copyright */}
        <footer className="w-full max-w-md mx-auto text-center py-8 text-xs text-slate-600 border-t border-white/5 relative z-10 bg-[#020215]">
          <p>&copy; {new Date().getFullYear()} MusicBox. Todos os direitos reservados.</p>
        </footer>
      </body>
    </html>
  );
}
